version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.2.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # rango de puertos de servicios externos
    volumes:
      - ./resources:/usr/tmp/resources # carpeta con archivos de ejemplo
      - ./localstack/init:/etc/localstack/init # comandos que se ejecutan cuando inicia el contenedor de LocalStack
